---
kind: pipeline
name: default

steps:
  - name: build docker image
    image: docker:dind
    volumes:
      - name: dockersock
        path: /var/run
    commands: |
      sleep 5 # give docker enough time to start
      docker ps -a
      if echo "${DRONE_TAG}" | grep -Eq "chart-[0-9]+(\.[0-9]+)*(-[a-z]+)?$"; then
        #REPOSITORY="https://fluxcdbot:${GITHUB_TOKEN}@github.com/fluxcd/charts.git"
        #mkdir $HOME/fluxcd-charts
        #cd $HOME/fluxcd-charts && git clone ${REPOSITORY}
        #cd $HOME/fluxcd-charts/charts
        #git checkout gh-pages
        #mv $HOME/chart/*.tgz .
        helm repo index . --url https://4nte.github.io/mq/
        #helm repo index . --url https://charts.fluxcd.io
        #git add .
        #git commit -m "Publish chart to fluxcd/charts"
        #git push origin gh-pages
        #else
        #echo "Not a chart release! Skip chart publish"
      fi

      export IMAGE_TAG=$docker-tag
      make docker-image-ci

services:
  - name: docker
    image: docker:dind
    privileged: true
    volumes:
      - name: dockersock
        path: /var/run

volumes:
  - name: dockersock
    temp: {}