version: 2

before:
  hooks:
  - go mod tidy
  - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  ldflags:
  - -s -w -X github.com/4nte/mqtt-mirror/cmd.version={{.Version}}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

dockers:
# Docker Hub - amd64
- goos: linux
  goarch: amd64
  ids:
  - mqtt-mirror
  image_templates:
  - "antegulin/mqtt-mirror:latest-amd64"
  - "antegulin/mqtt-mirror:{{ .Tag }}-amd64"
  - "antegulin/mqtt-mirror:{{ .Version }}-amd64"
  - "antegulin/mqtt-mirror:v{{ .Major }}-amd64"
  skip_push: false
  dockerfile: Dockerfile
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source=https://github.com/4nte/mqtt-mirror"

# Docker Hub - arm64
- goos: linux
  goarch: arm64
  ids:
  - mqtt-mirror
  image_templates:
  - "antegulin/mqtt-mirror:latest-arm64"
  - "antegulin/mqtt-mirror:{{ .Tag }}-arm64"
  - "antegulin/mqtt-mirror:{{ .Version }}-arm64"
  - "antegulin/mqtt-mirror:v{{ .Major }}-arm64"
  skip_push: false
  dockerfile: Dockerfile
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source=https://github.com/4nte/mqtt-mirror"

# GHCR - amd64
- goos: linux
  goarch: amd64
  ids:
  - mqtt-mirror
  image_templates:
  - "ghcr.io/4nte/mqtt-mirror:latest-amd64"
  - "ghcr.io/4nte/mqtt-mirror:{{ .Tag }}-amd64"
  - "ghcr.io/4nte/mqtt-mirror:{{ .Version }}-amd64"
  - "ghcr.io/4nte/mqtt-mirror:v{{ .Major }}-amd64"
  dockerfile: Dockerfile
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source=https://github.com/4nte/mqtt-mirror"

# GHCR - arm64
- goos: linux
  goarch: arm64
  ids:
  - mqtt-mirror
  image_templates:
  - "ghcr.io/4nte/mqtt-mirror:latest-arm64"
  - "ghcr.io/4nte/mqtt-mirror:{{ .Tag }}-arm64"
  - "ghcr.io/4nte/mqtt-mirror:{{ .Version }}-arm64"
  - "ghcr.io/4nte/mqtt-mirror:v{{ .Major }}-arm64"
  dockerfile: Dockerfile
  build_flag_templates:
  - "--pull"
  - "--label=org.opencontainers.image.created={{.Date}}"
  - "--label=org.opencontainers.image.name={{.ProjectName}}"
  - "--label=org.opencontainers.image.revision={{.FullCommit}}"
  - "--label=org.opencontainers.image.version={{.Version}}"
  - "--label=org.opencontainers.image.source=https://github.com/4nte/mqtt-mirror"

docker_manifests:
# Docker Hub
- name_template: "antegulin/mqtt-mirror:{{ .Version }}"
  image_templates:
  - "antegulin/mqtt-mirror:{{ .Version }}-amd64"
  - "antegulin/mqtt-mirror:{{ .Version }}-arm64"
- name_template: "antegulin/mqtt-mirror:{{ .Tag }}"
  image_templates:
  - "antegulin/mqtt-mirror:{{ .Tag }}-amd64"
  - "antegulin/mqtt-mirror:{{ .Tag }}-arm64"
- name_template: "antegulin/mqtt-mirror:latest"
  image_templates:
  - "antegulin/mqtt-mirror:latest-amd64"
  - "antegulin/mqtt-mirror:latest-arm64"
- name_template: "antegulin/mqtt-mirror:v{{ .Major }}"
  image_templates:
  - "antegulin/mqtt-mirror:v{{ .Major }}-amd64"
  - "antegulin/mqtt-mirror:v{{ .Major }}-arm64"
# GHCR
- name_template: "ghcr.io/4nte/mqtt-mirror:{{ .Version }}"
  image_templates:
  - "ghcr.io/4nte/mqtt-mirror:{{ .Version }}-amd64"
  - "ghcr.io/4nte/mqtt-mirror:{{ .Version }}-arm64"
- name_template: "ghcr.io/4nte/mqtt-mirror:{{ .Tag }}"
  image_templates:
  - "ghcr.io/4nte/mqtt-mirror:{{ .Tag }}-amd64"
  - "ghcr.io/4nte/mqtt-mirror:{{ .Tag }}-arm64"
- name_template: "ghcr.io/4nte/mqtt-mirror:latest"
  image_templates:
  - "ghcr.io/4nte/mqtt-mirror:latest-amd64"
  - "ghcr.io/4nte/mqtt-mirror:latest-arm64"
- name_template: "ghcr.io/4nte/mqtt-mirror:v{{ .Major }}"
  image_templates:
  - "ghcr.io/4nte/mqtt-mirror:v{{ .Major }}-amd64"
  - "ghcr.io/4nte/mqtt-mirror:v{{ .Major }}-arm64"

brews:
- repository:
    owner: 4nte
    name: homebrew-tap
  commit_author:
    name: goreleaserbot
    email: gnante0@gmail.com
  homepage: "https://github.com/4nte/mqtt-mirror"
  description: "Replicate MQTT traffic from one broker to another."
