{{- if not .Values.mqtt.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mqtt-mirror.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mqtt-mirror.name" . }}
    helm.sh/chart: {{ include "mqtt-mirror.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  SOURCE: {{ required ".Values.mqtt.source must be specified!" .Values.mqtt.source | b64enc | quote }}
  TARGET: {{ required ".Values.mqtt.target must be specified!" .Values.mqtt.target | b64enc | quote }}
{{- end }}
