{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "mqtt-mirror.fullname" . }}
  labels:
    {{- include "mqtt-mirror.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: health
      interval: {{ .Values.serviceMonitor.interval }}
      path: /metrics
  selector:
    matchLabels:
      {{- include "mqtt-mirror.selectorLabels" . | nindent 6 }}
{{- end }}
