{{- if .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt-mirror.fullname" . }}
  labels:
    {{- include "mqtt-mirror.labels" . | nindent 4 }}
spec:
  ports:
    - name: health
      port: {{ .Values.health.port }}
      targetPort: health
      protocol: TCP
  selector:
    {{- include "mqtt-mirror.selectorLabels" . | nindent 4 }}
{{- end }}
