{{- if .Values.serviceMonitor.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mqtt-mirror.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mqtt-mirror.name" . }}
    helm.sh/chart: {{ include "mqtt-mirror.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ports:
    - name: health
      port: {{ .Values.health.port }}
      targetPort: health
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "mqtt-mirror.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
