{{- define "helm-toolkit.utils.joinListWithComma" -}}
{{- $local := dict "first" true -}}
{{- range $k, $v := . -}}{{- if not $local.first -}},{{- end -}}{{- $v -}}{{- $_ := set $local "first" false -}}{{- end -}}
{{- end -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mqtt-mirror.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mqtt-mirror.name" . }}
    helm.sh/chart: {{ include "mqtt-mirror.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mqtt-mirror.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mqtt-mirror.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SOURCE
              value: "{{ required ".Values.mqtt.source must be specified!" .Values.mqtt.source }}"
            - name: TARGET
              value: "{{ required ".Values.mqtt.target must be specified!" .Values.mqtt.target }}"
            - name: TOPIC_FILTER
              value: "{{ include "helm-toolkit.utils.joinListWithComma" .Values.mqtt.topic_filter }}"
            {{ if .Values.verbose }}
            - name: VERBOSE
              value: "{{ .Values.verbose }}"
            {{end}}
            {{ if .Values.name }}
            - name: NAME
              value: "{{ .Values.name }}"
            {{end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
