name: Build docker image (Release)
on:
  push:
    branches:
      - 'release/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: antegulin/mqtt-mirror
          tag: ${{GIT_REF}}
          registry: docker.io
          dockerfile: build/Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}