name: Helm publish
on:
  push:
    branches: [master]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo
        with:
          path: code-repo
        uses: actions/checkout@v2
      - name: Checkout helm package repository repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: '4nte/helm-charts'
          path: helm-repo
      - name:  Create helm package
        uses: stefanprodan/kube-tools@v1
        with:
          helm: 2.16.1
          command: |
            cd /github/workspace/code-repo
            echo "-- Code repo ---"
            helm package chart/mqtt-mirror --destination /github/workspace/helm-repo
            helm repo index /github/workspace/helm-repo --url https://rvgud.github.io/kube-curator/

            cd /github/workspace/helm-repo
            echo "-- Helm repo ---"
            ls