name: Helm publish
on:
  push:
    branches: [master]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Checkout helm repository repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: '4nte/helm-charts'
      - name:
        uses: stefanprodan/kube-tools@v1
        with:
          helm: 2.16.1
          command: |
            pwd
            ls

