name: Helm publish
on:
  push:
    branches: [master]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repo
        with:
          path: code-repo
        uses: actions/checkout@v2
      - name: Checkout helm package repository repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: '4nte/helm-charts'
          path: helm-repo
      - name:  Create helm package
        uses: stefanprodan/kube-tools@v1
        with:
          helm: 2.16.1
          command: |
            cd /github/workspace/code-repo
            echo "-- Code repo ---"
            helm init --client-only
            mkdir -p /github/workspace/helm-repo/charts/mqt-mirror
            helm package chart/mqtt-mirror --destination /github/workspace/helm-repo/charts/mqtt-mirror
            helm repo index /github/workspace/helm-repo --url https://4nte.github.io/helm-charts/

            cd /github/workspace/helm-repo
            echo "-- Helm repo ---"
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "release helm chart" -a
            git push -u origin master
            ls