name: Release with goreleaser
on:
  push:
    branches:
    - "!*"
    tags:
    - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
    - id: get_version
      uses: battila7/get-version-action@v2
    - run: echo ${{ steps.get_version.outputs.version-without-v }}
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
        path: mqtt-mirror
        fetch-depth: 0

    - name: Docker Login
      if: success() && startsWith(github.ref, 'refs/tags/')
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

    - name: goreleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        args: release
        workdir: ${{github.workspace}}/mqtt-mirror
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}

    - name: Publish helm chart
      uses: stefanprodan/helm-gh-pages@v1.4.1
      with:
        token: ${{ secrets.PAT }}
        repository: 4nte/helm-charts
        chart_version: ${{ steps.get_version.outputs.version-without-v }}
        app_version: ${{ steps.get_version.outputs.version-without-v }}
