name: Release with goreleaser
on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    name: goreleaser
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --depth=10000

      - name: goreleaser
        uses: goreleaser/goreleaser-action@master
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      - name: Checkout helm package repository repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          repository: '4nte/helm-charts'
          path: helm-repo

      - name:  Create helm package
        uses: stefanprodan/kube-tools@v1
        with:
          helm: 2.16.1
          command: |
            export SEMVER=${GIT_REF/#"v"}
            echo "semver $SEMVER"
            cd /github/workspace/code-repo
            echo "-- Code repo ---"
            helm init --client-only
            mkdir -p /github/workspace/helm-repo/charts/mqtt-mirror
            helm package chart/mqtt-mirror --destination /github/workspace/helm-repo/charts/mqtt-mirror --version $SEMVER
            helm repo index /github/workspace/helm-repo --url https://4nte.github.io/helm-charts/
            cd /github/workspace/helm-repo
            echo "-- Helm repo ---"
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add .
            git commit -m "release helm chart" -a
            git push -u origin master
